"""Nameplate partial — station-agnostic defaults over the generated IDTA template.

Uses the Nameplate template generated by our aas_pydantic fork
(``aas_pydantic.submodel_templates.nameplate``).  Field names == the IDTA
idShorts with their STANDARD casing (``URIOfTheProduct``, ``ManufacturerName``,
``AddressInformation``, ``Street``/``Zipcode``/``CityTown``/``NationalCode``, …)
so the built AAS idShorts match what standard consumers (e.g. the BaSyx Web UI
Digital Nameplate plugin) look up.  The template marks five children as
mandatory (One): URIOfTheProduct, ManufacturerName,
ManufacturerProductDesignation, AddressInformation, OrderCodeOfManufacturer.
These are provided here as the resource-type baseline (stations override them
via ``model_validate()``); the station-specific optional children
(SerialNumber, YearOfConstruction, CountryOfOrigin, …) are set below.

Named-field style: children are DIRECT named fields on the container (no
``submodel_element``/``value`` wrapper).
"""

from __future__ import annotations

from aas_pydantic.submodel_templates.nameplate import (
    Nameplate,
    URIOfTheProduct, ManufacturerName, ManufacturerProductDesignation,
    AddressInformation,
    Street, Zipcode, CityTown, NationalCode,
    OrderCodeOfManufacturer,
    YearOfConstruction, CountryOfOrigin,
)


def nameplate() -> Nameplate:
    """Nameplate with station-agnostic defaults (rest comes from the template)."""
    np = Nameplate(
        id_short="Nameplate",
        URIOfTheProduct=URIOfTheProduct(
            value="https://smartproductionlab.aau.dk/product/1"
        ),
        ManufacturerName=ManufacturerName(
            value={"en": "AAU Smart Production Lab"}
        ),
        ManufacturerProductDesignation=ManufacturerProductDesignation(
            value={"en": "Pharmaceutical Processing Resource"}
        ),
        AddressInformation=AddressInformation(
            Street=Street(value={"en": "Fibigerstræde 14"}),
            Zipcode=Zipcode(value={"en": "9220"}),
            CityTown=CityTown(value={"en": "Aalborg Øst"}),
            NationalCode=NationalCode(value={"en": "DK"}),
        ),
        OrderCodeOfManufacturer=OrderCodeOfManufacturer(value=""),
    )
    np.YearOfConstruction = YearOfConstruction(value="2026")
    np.CountryOfOrigin = CountryOfOrigin(value="DK")
    return np
