"""Nameplate partial — station-agnostic defaults over the generated IDTA template.

Uses the Nameplate template generated by our aas_pydantic fork
(``aas_pydantic.submodel_templates.nameplate``).  The template marks five
children as mandatory (One): u_r_i_of_the_product, manufacturer_name,
manufacturer_product_designation, address_information, order_code_of_manufacturer.
``address_information`` carries the SMT drop-in "Address Information" (Street /
Zipcode / CityTown / NationalCode mandatory, AddressOfAdditionalLink optional).
These are provided here as the resource-type baseline (stations override them
via ``model_validate()``); the station-specific optional children
(serial_number, year_of_construction, country_of_origin, …) are set below.

Named-field style: children are DIRECT named fields on the container (no
``submodel_element``/``value`` wrapper).
"""

from __future__ import annotations

from aas_pydantic.submodel_templates.nameplate import (
    Nameplate,
    URIOfTheProduct, ManufacturerName, ManufacturerProductDesignation,
    AddressInformation,
    Street, Zipcode, CityTown, NationalCode,
    OrderCodeOfManufacturer,
    YearOfConstruction, CountryOfOrigin,
)


def nameplate() -> Nameplate:
    """Nameplate with station-agnostic defaults (rest comes from the template)."""
    np = Nameplate(
        id_short="Nameplate",
        u_r_i_of_the_product=URIOfTheProduct(
            value="https://smartproductionlab.aau.dk/product/1"
        ),
        manufacturer_name=ManufacturerName(
            value={"en": "AAU Smart Production Lab"}
        ),
        manufacturer_product_designation=ManufacturerProductDesignation(
            value={"en": "Pharmaceutical Processing Resource"}
        ),
        address_information=AddressInformation(
            street=Street(value={"en": "Nybrovej 114"}),
            zipcode=Zipcode(value={"en": "9220"}),
            city_town=CityTown(value={"en": "Aalborg Øst"}),
            national_code=NationalCode(value={"en": "DK"}),
        ),
        order_code_of_manufacturer=OrderCodeOfManufacturer(value=""),
    )
    np.year_of_construction = YearOfConstruction(value="2026")
    np.country_of_origin = CountryOfOrigin(value="DK")
    return np
